BEGIN;

CREATE TABLE IF NOT EXISTS site_images (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slot_key VARCHAR(80) NOT NULL UNIQUE,
  label VARCHAR(150) NOT NULL,
  photo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT SELECT ON site_images TO homepage_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON site_images TO homepage_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO homepage_admin;

COMMIT;
