INSERT INTO professor_activities (period, detail) VALUES
  ('2013-현재', '연세대학교 정보대학원 정교수'),
  ('2020-현재', '연세대학교 인공지능대학원 AI+X 겸직교수'),
  ('2024-현재', '연세대학교 교무처 교수학습혁신센터장'),
  ('2024-현재', '연세대학교 LearnUs 추진본부 교과분야 단장'),
  ('2024-현재', '연세대학교 지능형혁신연구소 소장'),
  ('2024-현재', '한국정보보학회 AI보안연구회 위원장'),
  ('2006-현재', '한국정보보호학회 상임이사'),
  ('2003-현재', '한국정보보호학회 논문지 편집위원'),
  ('2007-현재', '정보과학회 논문지 편집위원'),
  ('2008-현재', '한국정보보호학회 암호연구회 운영위원'),
  ('2006-현재', '대검찰청 디지털수사 자문위원'),
  ('2021-현재', '국민생활과학자문단 사이버안전분과 위원'),
  ('2022-현재', '에스알 AI빅데이터 분과 위원'),
  ('2024-현재', '경찰청 디지털포렌식 자문위원'),
  ('2024-현재', '경찰청 사이버성폭력 수사 자문위원'),
  ('2022-현재', '서울시 개인정보보호 심의위원'),
  ('2025-현재', '금융보안원 자문위원'),
  ('2025-현재', '금융감독원 자문위원'),
  ('2025-현재', '국가 딥페이크 대응 자문위원회 위원장'),
  ('2026-현재', '개인정보보호위원회 인공지능 프라이버시 위원'),
  ('2026-현재', '한국인터넷진흥원 램섬웨어 전주기 대응 위원'),
  ('2026-현재', '국가인공지능전략위원회 보안TF 위원')
ON CONFLICT (detail) DO UPDATE SET
  period = EXCLUDED.period,
  updated_at = NOW();

INSERT INTO professor_career (period, detail) VALUES
  ('1999-2000', 'Univ. of California at Berkeley, 포스트닥'),
  ('2001-2013', '세종대학교 컴퓨터공학과 교수'),
  ('2007-2008', 'Univ. of Maryland at College Park, 교환교수'),
  ('2009-2010', '세종대학교 컴퓨터공학과 컴퓨터소프트웨어전공 학과장'),
  ('2011-2012', '세종대학교 정보보호학과 학과장'),
  ('2013-2018', '연세대학교 지식서비스보안과정 주임교수'),
  ('2015-2018', '연세대학교 디지털포렌식 경찰청계약학과 주임교수'),
  ('2016-2019', '연세대학교 IT정책전략연구소 소장'),
  ('2022-2024', '연세대학교 글로벌인재대학 응용정보공학 책임교수'),
  ('2022-2024', '연세대학교 교보AI빅데이터학과 주임교수'),
  ('2016-2017', '정보과학회 이사'),
  ('2021-2024', '한국연구재단 기초연구본부 전문위원'),
  ('2022-2026', '경찰청 자체평가위원회 위원')
ON CONFLICT (detail) DO UPDATE SET
  period = EXCLUDED.period,
  updated_at = NOW();

INSERT INTO professor_papers (paper_year, citation, link_url) VALUES
  (2024, 'Jeewoo Jung, Taekyoung Kwon, "Enhancing Differential Fuzzing of Cryptographic Libraries with Sustainable Hybrid Fuzzing and Crypto-Specific Mutation," in Proc. the Annual International Conference on Information Security and Cryptology (ICISC), Nov. 2024. (Best Paper Award)', NULL),
  (2024, 'Leo Hyun Park, Jaeuk Kim, Myung Gyo Oh, Jaewoo Park, and Taekyoung Kwon, "Adversarial Feature Alignment: Balancing Robustness and Accuracy in Deep Learning via Adversarial Training," in Proc. the 17th ACM Workshop on Artificial Intelligence and Security (AISec), Oct. 2024.', NULL),
  (2024, 'Jueon Eom, Seyeon Jeong, and Taekyoung Kwon, "Fuzzing JavaScript Interpreters with Coverage-Guided Reinforcement Learning for LLM-based Mutation," in Proc. the 33rd ACM SIGSOFT International Symposium on Software Testing and Analysis (ISSTA), Sep. 2024.', NULL),
  (2023, 'Mingi Cho, Dohyeon An, Hoyong Jin, and Taekyoung Kwon, "BoKASAN: Binary-only Kernel Address Sanitizer for Effective Kernel Fuzzing," 32nd USENIX Security Symposium (USENIX Security), Aug. 2023.', NULL),
  (2023, 'Leo Hyun Park, Soochang Chung, Jaeuk Kim, and Taekyoung Kwon, "GradFuzz: Fuzzing Deep Neural Networks with Gradient Vector Coverage for Adversarial Examples," Neurocomputing, Elsevier, Vol.522, pp.165-180, Feb. 2023.', NULL),
  (2022, 'Hoyong Jin, Dohyeon An, and Taekyoung Kwon, "Differential Testing of Cryptographic Libraries with Hybrid Fuzzing," Proc. the Annual International Conference on Information Security and Cryptology (ICISC), Nov. 2022. (Best Paper Award)', NULL),
  (2022, 'Leo Hyun Park, Eunbi Hwang, Donggun Lee, and Taekyoung Kwon, "Towards Constructing Consistent Pattern Strength Meters with User’s Visual Perception," Proc. the Annual International Conference on Information Security and Cryptology (ICISC), Nov. 2022.', NULL),
  (2022, 'Leo Hyun Park, Jaeuk Kim, Jaewoo Park, and Taekyoung Kwon, "Mixed and Constrained Input Mutation for Effective Fuzzing of Deep Learning Systems," Information Sciences, Elsevier, Vol.614, pp.497-517, Oct. 2022.', NULL),
  (2020, 'Leo Hyun Park, Jungbeen Yu, Hong-Koo Kang, Taejin Lee, and Taekyoung Kwon, "Birds of a Feature: Intrafamily Clustering for Version Identification of Packed Malware," IEEE Systems Journal, Vol.14, pp.4545-4556, Sep. 2020.', NULL),
  (2021, 'Mingi Cho, Jaedong Jang, Yezee Seo, Seyeon Jeong, Soochang Chung, and Taekyoung Kwon, "Towards Bidirectional LUT-level Detection of Hardware Trojans," Computers & Security, Elsevier, Vol.104, May 2021.', NULL),
  (2019, 'Mingi Cho, Seoyoung Kim, and Taekyoung Kwon, "Intriguer: Field-Level Constraint Solving for Hybrid Fuzzing," Proc. the ACM Conference on Computer and Communications Security (ACM CCS), pp.515-530, Nov. 2019.', NULL),
  (2017, 'Hoyong Lee, Seungyeon Kim, and Taekyoung Kwon, "Here Is Your Fingerprint! Actual Risk versus User Perception of Latent Fingerprints and Smudges Remaining on Smartphones," Proc. the 33rd Annual Computer Security Applications Conference (ACSAC), Orlando, Florida, pp.512-527, Dec. 2017.', NULL),
  (2016, 'Taekyoung Kwon and Sarang Na, "SteganoPIN: Two-Faced Human-Machine Interface for Practical Enforcement of PIN Entry Security," IEEE Trans. on Human-Machine Systems, Vol.46, No.1, pp.143-150, February 2016.', NULL),
  (2016, 'Jonghyup Lee, Leehyung Kim, and Taekyoung Kwon, "FlexiCast: Energy-Efficient Software Integrity Checks to Build Secure Industrial Wireless Active Sensor Networks," IEEE Trans. on Industrial Informatics, Vol.12, No.4, pp.6-14, 2016.', NULL),
  (2015, 'Taekyoung Kwon and Jin Hong, "Analysis and Improvement of a PIN-Entry Method Resilient to Shoulder-Surfing and Recording Attacks," IEEE Trans. on Information Forensics and Security, Vol.10, No.2, pp.278-292, February 2015.', NULL),
  (2014, 'Taekyoung Kwon, Sooyeon Shin, and Sarang Na, "Covert Attentional Shoulder Surfing: Human Adversaries Are More Powerful Than Expected," IEEE Trans. on Systems, Man, and Cybernetics Systems (Formerly Part A), Vol.44, No.6, pp.716-727, June 2014.', NULL),
  (2014, 'Taekyoung Kwon and Sarang Na, "TinyLock: Affordable Defense Against Smudge Attacks on Smartphone Pattern Lock Systems," Computers & Security, Elsevier, Vol.42, pp.137-150, May 2014.', NULL),
  (2011, 'Taekyoung Kwon, "Privacy Preservation with X.509 Standard Certificates," Information Sciences, Elsevier, Vol.181, No.13, pp.2906-2921, July 2011.', NULL),
  (2011, 'Junghae Cheon, Stanislav Jarecki, Taekyoung Kwon, and Mun-Kyu Lee, "Fast Exponentiation Using Split Exponents," IEEE Trans. on Information Theory, Vol.57, No.3, pp.1816-1826, March 2011.', NULL),
  (2010, 'Sooyeon Shin, Taekyoung Kwon, Gil-yong Jo, Youngman Park, and Haekyu Rhy, "An Experimental Study of Hierarchical Intrusion Detection for Wireless Industrial Sensor Networks," IEEE Trans. on Industrial Informatics, Vol.6, No.4, pp.744-757, November 2010.', NULL),
  (2010, 'Taekyoung Kwon and Jin Hong, "Secure and Efficient Broadcast Authentication in Wireless Sensor Networks," IEEE Trans. on Computers, Vol.59, No.8, pp.1120-1133, August 2010.', NULL),
  (2010, 'JongHyup Lee, Taekyoung Kwon, and JooSeok Song, "Group Connectivity Model for Industrial Wireless Sensor Networks," IEEE Trans. on Industrial Electronics, Vol.57, No.5, pp.1835-1844, July 2010.', NULL),
  (2009, 'Taekyoung Kwon, JongHyup Lee, and JooSeok Song, "Location-based Pairwise Key Predistribution for Wireless Sensor Networks," IEEE Trans. on Wireless Communications, Vol.8, No.11, pp.5436-5442, November 2009.', NULL),
  (2008, 'Taekyoung Kwon and Hyeonjoon Moon, "Biometric Authentication for Border Control Applications," IEEE Trans. on Knowledge and Data Engineering, Vol.20, No.8, pp.1091-1096, August 2008.', NULL),
  (2007, 'Taekyoung Kwon, Hyungwoo Lee, and Jae-il Lee, "A Practical Method for Generating Digital Signatures Using Biometrics," IEICE Trans. on Communications, Vol.E90-B, No.6, pp.1381-1389, 2007.', NULL),
  (2007, 'Jiyong Jang, Taekyoung Kwon, and Jooseok Song, "A Time-based Key Management Protocol for Wireless Sensor Networks," Information Security Practice and Experience, Lecture Notes in Computer Science, Vol.4464, Springer-Verlag, pp.314-328, 2007.', NULL),
  (2006, 'Chaehoon Lim and Taekyoung Kwon, "Strong and Robust RFID Authentication Enabling Perfect Ownership Transfer," Information and Communications Security, Lecture Notes in Computer Science, Vol.4307, Springer-Verlag, pp.1-20, 2006.', NULL),
  (2004, 'Taekyoung Kwon, "Practical Authenticated Key Agreement Using Passwords," Information Security, Lecture Notes in Computer Science, Vol.3225, Springer-Verlag, pp.1-12, September 2004.', NULL),
  (2004, 'Taekyoung Kwon, "Refinement and Improvement of Virtual Software Token Protocols," IEEE Communications Letters, Vol.8, No.1, pp.75-77, January 2004.', NULL),
  (2001, 'Taekyoung Kwon, "Authentication and Key Agreement via Memorable Password," Proc. of NDSS (Network and Distributed Systems Security), February 2001. (IEEE P1363.2 and ISO/IEC 11770-4 Proposal)', NULL),
  (1999, 'Taekyoung Kwon and Jooseok Song, "Secure Agreement Scheme for gxy via Password Authentication," IEE Electronics Letters, Vol.35, No.11, pp.892-893, May 1999.', NULL),
  (1997, 'Taekyoung Kwon, Myeongho Kang, and Jooseok Song, "An Adaptable and Reliable Authentication Protocol for Communication Networks," Proc. of IEEE INFOCOM 97, pp.738-745, April 1997.', NULL)
ON CONFLICT (citation) DO UPDATE SET
  paper_year = EXCLUDED.paper_year,
  updated_at = NOW();
