INSERT INTO students (course, name, note, photo_url) VALUES
  ('phd', 'LEOHYUN PARK', NULL, '/images/students/leohyun-park.jpg'),
  ('phd', 'YOONSIK KIM', NULL, '/images/students/yoonsik-kim.jpg'),
  ('phd', 'EUNBI HWANG', NULL, '/images/students/eunbi-hwang.jpg'),
  ('phd', 'BYUNGCHUL KIM', NULL, '/images/students/byungchul-kim.jpg'),
  ('phd', 'SANGSOO HAN', NULL, '/images/students/sangsoo-han.jpg'),
  ('phd', 'NARAE KANG', '(Part)', '/images/students/narae-kang.jpg'),
  ('master', 'GYUHWAN KIM', NULL, '/images/students/gyuhwan-kim.jpg'),
  ('master', 'HYEOKJOO KWON', NULL, '/images/students/hyeokjoo-kwon.jpg'),
  ('master', 'JIHYEOK CHOI', NULL, '/images/students/jihyeok-choi.png'),
  ('master', 'YOONDONG YEO', NULL, '/images/students/yoondong-yeo.jpg'),
  ('master', 'SHINYOUNG WON', NULL, '/images/students/shinyoung-won.jpg'),
  ('master', 'YEONKYO JUNG', '(Part)', '/images/students/yeonkyo-jung.jpg'),
  ('master', 'MINJUN SUN', NULL, '/images/students/minjun-sun.jpg'),
  ('master', 'GIWON KANG', NULL, '/images/students/giwon-kang.jpg'),
  ('master', 'YUNSEO LEE', NULL, '/images/students/yunseo-lee.jpg')
ON CONFLICT DO NOTHING;

INSERT INTO alumni (school, degree, name, company, graduated_year, graduated_semester) VALUES
  ('연세대학교', 'Ph.D.', '조민기', '티오리(병역특례)', 2023, 1),
  ('연세대학교', 'M.S.', '정지우', '국가보안기술연구소', 2024, 2),
  ('연세대학교', 'M.S.', '오명교', 'KT', 2024, 1),
  ('연세대학교', 'M.S.', '박재우', '씨이랩(병역특례)', 2023, 2),
  ('연세대학교', 'M.S.', '임은지', '엔아이티서비스', 2023, 2),
  ('연세대학교', 'M.S.', '엄주언', '안랩', 2023, 2),
  ('연세대학교', 'M.S.', '진호용', '아우토크립트(병역특례)', 2023, 2),
  ('연세대학교', 'M.S.', '안도현', '코인원(병역특례)', 2023, 1),
  ('연세대학교', 'M.S.', '윤혜민', '삼정KPMG', 2023, 1),
  ('연세대학교', 'M.S.', '정세연', '슈어소프트테크', 2023, 1),
  ('연세대학교', 'M.S.', '정수창', '베이글코드(인턴)', 2023, 1),
  ('연세대학교', 'M.S.', '김해니', '김앤장 법률사무소', 2022, 2),
  ('연세대학교', 'M.S.', '김서영', '삼성전자', 2022, 2),
  ('연세대학교', 'M.S.', '김종신', '딥테크인컴퍼니', 2022, 2),
  ('연세대학교', 'M.S.', '오상진', '현대엔지니어링', 2022, 2),
  ('연세대학교', 'M.S.', '구예은', '우리은행', 2022, 1),
  ('연세대학교', 'M.S.', '김슬기', '한국정보통신기술협회(TTA)', 2022, 1),
  ('연세대학교', 'M.S.', '장재동', '한국인터넷진흥원(KISA)', 2022, 1),
  ('연세대학교', 'M.S.', '윤정환', '네이버', 2022, 1),
  ('연세대학교', 'M.S.', '서예지', '안랩', 2021, 2),
  ('연세대학교', 'M.S.', '유정빈', '피플펀드', 2021, 2),
  ('연세대학교', 'M.S.', '신민식', '삼성전자', 2021, 1),
  ('연세대학교', 'M.S.', '이영주', '로드맵', 2021, 1),
  ('연세대학교', 'M.S.', '이호연', '네이버', 2021, 1),
  ('연세대학교', 'M.S.', '김민우', 'SK주식회사 C&C', 2020, 2),
  ('연세대학교', 'M.S.', '김경훈', 'NICE 평가정보', 2020, 2),
  ('연세대학교', 'M.S.', '양원석', 'Univ. of Oklahoma', 2020, 2),
  ('연세대학교', 'M.S.', '정성미', '포스코(POSCO)', 2020, 1),
  ('연세대학교', 'M.S.', '조현웅', '우정사업본부', 2020, 1),
  ('연세대학교', 'M.S.', '윤영진', '한화 S&C', 2019, 2),
  ('연세대학교', 'M.S.', '유홍렬', '지니언스', 2019, 2),
  ('연세대학교', 'M.S.', '방지현', '코나아이(Konai)', 2019, 2),
  ('연세대학교', 'M.S.', '노승훈', '카카오', 2019, 1),
  ('연세대학교', 'M.S.', '최재우', '한국인터넷진흥원(KISA)', 2019, 1),
  ('연세대학교', 'M.S.', '홍모세', '펜타시큐리티', 2019, 1),
  ('연세대학교', 'M.S.', '현석우', '국가보안기술연구소', 2019, 1),
  ('연세대학교', 'M.S.', '이동건', '국방부', 2018, 2),
  ('연세대학교', 'M.S.', '이준원', '삼성전자', 2018, 2),
  ('연세대학교', 'M.S.', '김승연', '넷엔드(병역특례)', 2018, 1),
  ('세종대학교', 'Ph.D.', '박상호', '한국정보통신기술협회(TTA)', 2017, 2),
  ('세종대학교', 'Ph.D.', '신수연', '연세대학교 (포스트닥)', 2017, 2),
  ('세종대학교', 'M.S.', '나사랑', '한국인터넷진흥원(KISA), 연세대학교 박사과정(파트)', 2017, 2),
  ('세종대학교', 'M.S.', '최원석', '유비벨록스 모바일 | 선임연구원', 2017, 2),
  ('세종대학교', 'M.S.', '송성현', '금융보안연구원 | 주임연구원', 2017, 1),
  ('세종대학교', 'M.S.', '조길용', '유비벨록스 모바일 | 선임연구원', 2017, 1),
  ('세종대학교', 'M.S.', '정연호', '유비벨록스 | 과장', 2017, 1),
  ('세종대학교', 'M.S.', '김수희', '한영회계법인 | Senior', 2016, 2),
  ('세종대학교', 'M.S.', '김문권', '(주)에고소프트 | 과장', 2016, 2),
  ('세종대학교', 'M.S.', '송현수', '유비벨록스', 2016, 2),
  ('세종대학교', 'M.S.', '이영권', '한국정보통신기술협회(TTA) | 센터장', 2016, 2),
  ('세종대학교', 'M.S.', '정재웅', 'GMT소프트 | 팀장', 2016, 2)
ON CONFLICT DO NOTHING;

